
"""
/*FATURAMENTO POR CLIENTE */
SELECT C.NOME AS CLIENTE, SUM(P.PRECO * V.QUANTIDADE) AS FATURAMENTO
FROM VENDAS V
JOIN CLIENTES C
ON C.IDCLIENTE = V.ID_CLIENTE
JOIN PRODUTOS P 
ON P.IDPRODUTO = V.ID_PRODUTO
GROUP BY C.NOME
ORDER BY FATURAMENTO DESC;

/*PRODUTOS MAIS VENDIDOS */
SELECT P.NOME AS PRODUTO, SUM(V.QUANTIDADE) AS TOTAL_VENDIDOS
FROM VENDAS V
JOIN PRODUTOS P
ON V.ID_PRODUTOS = P.IDPRODUTOS
GROUP BY P.NOME
ORDER BY TOTAL_VENDIDOS DESC;

/*FATURAMENTO TOTAL POR PRODUTO*/
SELECT P.NOME AS PRODUTO, SUM(V.QUANTIDADE * P.PRCECO) AS FATURAMENTO
FROM VENDAS V
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.IDPRODUTO 
GROUP BY P.NOME
ORDER BY FATURAMENTO DESC;

/*FATURAMENTO MENSAL*/
SELECT DATE_TRUNC("MONTH", V.DATA) AS MES, SUM(V.QUANTIDADE * P.PRECO) AS FATURAMENTO
FROM VENDAS V
JOIN PRODUTOS P
ON P.IDPRODUTO = V.ID_PRODUTO
GROUP BY MES
ORDER BY MES;

/*TICKET MEDIO POR CLIENTE*/
SELECT C.NOME AS CLIENTE, AVG(V.QUANTIDADE * P.PRECO) AS MEDIA
FROM VENDAS V
JOIN CLIENTES C
ON C.IDCLIENTE = V.ID_CLIENTE
JOIN PRODUTOS P
ON P.IDPRODUTO = V.ID_PRODUTO
GROUP BY C.NOME
ORDER BY MEDIA DESC;
"""